### ISSUE TITLE
Favorite device hotkey/keyword

### ISSUE THREAD

**Issue by msimic-dev** [vitorgalvao/dente-azul-workflow#5]
### Feature details

A nice feature would be to connect/disconnect one specific device, only through one hotkey or keyword. It's would be useful for me, since I'm mostly using this workflow for my headphones. 

Configuration could happen through a small setup, where the user can configure which device should be the "favorite". If the device isn't available to connect, a short notification could appear.

**Comment by vitorgalvao** [comment]
That’s overly specific and would be very complex. It makes more sense for you make the workflow for it. Connect a [Hotkey Trigger](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to a [Run Script Action](https://www.alfredapp.com/help/workflows/actions/run-script/) with code `blueutil --connect "ADDRESS" --wait-connect "ADDRESS"`. To disconnect, replace `--connect` with `--disconnect`. You’ll have `blueutil` installed already, as it’s required for this workflow. Replace `ADDRESS` with the address from the device, which you can get by running `blueutil --connected`. If you’re on Apple Silicon, you may need to use `/opt/homebrew/bin/blueutil` instead of `blueutil` on the Terminal.
